"""PRO standalone preset — institutional-style discipline."""

PRO_STANDALONE_PRESET: dict = {
    "symbol": "AUTO",
    "usdtAmount": 50,
    "leverage": 5,
    "leverageMin": 3,
    "leverageMax": 25,
    "leverageAutoEnabled": True,
    "adaptiveLeverageEnabled": True,
    "adaptiveLeverageMax": 25,
    "marginType": "CROSSED",
    "takeProfitPct": 1.8,
    "stopLossPct": 0.9,
    "minRiskRewardRatio": 1.5,
    "atrTpSlEnabled": True,
    "ema200StrictEnabled": True,
    "intervalSec": 25,
    "minConfidence": 0.74,
    "htfStrictEnabled": True,
    "htfMinStrength": 0.22,
    "cooldownSec": 20,
    "maxTradesPerHour": 5,
    "allowFlip": False,
    "strongFlipEnabled": True,
    "strongFlipMinConfidence": 0.90,
    "strongFlipMinScoreGap": 1.5,
    "strongFlipUltraScoreGap": 2.2,
    "strongFlipUltraConfRelax": 0.08,
    "maxSpreadBps": 16,
    "maxSlippageBps": 18,
    "trailingStopPct": 0,
    "executionMode": "PAPER",
    "aggressiveScalp": False,
    "earlyEntryEnabled": True,
    "earlyEntryScoreGapMin": 1.4,
    "earlyEntryMinConfidence": 0.60,
    "lateEntryMaxBbPctB": 0.90,
    "lateEntryMaxVwapDistancePct": 0.32,
    "holdWinners": True,
    "holdMinConfidence": 0.78,
    "holdTrailPct": 0.32,
    "profitLockTriggerUsdt": 0.25,
    "profitLockKeepUsdt": 0.10,
    "profitLockMaxGivebackUsdt": 0.18,
    "marketScan": True,
    "scanTopLiquid": 25,
    "scanAnalyzeTop": 6,
    "scanPerSymbolTimeoutSec": 7.5,
    "scanFallbackNearEnabled": True,
    "scanFallbackNearConfRelax": 0.04,
    "volTargetEnabled": True,
    "volTargetPct": 0.2,
    "slToTpRatio": 0.5,
    "tpSlTargetUsdtEnabled": True,
    "tpTargetMinUsdt": 0.55,
    "tpTargetMaxUsdt": 2.2,
    "feeMinNetProfitUSDT": 0.06,
    "feeMinEdgeVsCostMultiple": 1.35,
    "pairLockEnabled": True,
    "pairLockLossStreak": 2,
    "pairLockMinutes": 60,
    "benchmarkFilterEnabled": True,
    "riskCooldownEnabled": False,
    "riskCooldownAdaptiveMarket": True,
    "riskCooldownAdaptiveCheckSec": 30,
    "riskCooldownPauseOnVolatile": True,
    "riskCooldownVolatileMinutes": 10,
    "riskCooldownResumeScoreGapMin": 2.0,
    "liveBadUtcHours": [],
    "maxDailyTradesPerSymbol": 14,
    "perfGateMinSamples": 8,
    "perfGateMinWinRatePct": 40,
    "perfGateMinPnlUsdt": -0.5,
    "perfLockMinutes": 90,
    "learningRewardEnabled": True,
    "learningBehaviorRewardEnabled": True,
    "memoryPrimaryDays": 7,
    "memoryConfirmDays": 15,
    "memoryBaselineDays": 30,
    "memoryArchiveWeightPct": 0.0,
    "learningRewardWin": 1.0,
    "learningPenaltyLoss": 0.8,
    "learningRewardDecay": 0.985,
    "learningRewardCap": 50.0,
    "learningPnlClipAbsUsdt": 25.0,
    "learningRewardEntryTiming": 0.25,
    "learningRewardHoldWinner": 0.2,
    "learningRewardTpHitBase": 0.2,
    "learningRewardTpScalePerUsdt": 0.35,
    "learningRewardFlipGood": 0.1,
    "learningPenaltyEarlySl": 0.35,
    "learningPenaltyMemoryMiss": 0.15,
    "learningBehaviorDeltaCap": 2.5,
    "learningFastWinMinutes": 45,
    "requireVisionConsensus": False,
}

PLAYBOOK: dict = {
    "version": "2.0",
    "philosophy": "Trade less, align more — confluence + HTF + macro EMA200 + fee-positive edge.",
    "layers": [
        {"id": "data", "name": "Market Data", "desc": "Klines 1m/5m/15m/1h, book, funding, mark"},
        {"id": "confluence", "name": "Confluence Engine", "desc": "Weighted L/S score → LONG/SHORT/WAIT"},
        {"id": "regime", "name": "Regime", "desc": "TREND / RANGE / VOLATILE → size & confidence adjust"},
        {"id": "gates", "name": "Entry Pipeline", "desc": "Ordered gates with audit trail before any order"},
        {"id": "risk", "name": "Risk Desk", "desc": "R:R ≥ min, ATR floor SL/TP, vol sizing, daily caps"},
        {"id": "execution", "name": "Execution", "desc": "Spread/slippage limits, LIVE guardian, profit lock"},
        {"id": "learn", "name": "Learning", "desc": "Obsidian trades → TP/SL tune + pattern bias"},
    ],
    "entryGates": [
        "signal",
        "spread",
        "confidence",
        "htf",
        "ema200",
        "funding",
        "slippage",
        "risk_reward",
        "fee_edge",
    ],
    "exitRules": [
        "TP with optional hold+trail when confluence still aligned",
        "SL with optional trend-pullback widen (bounded)",
        "Early exit when ≥2 adverse votes (opp signal, trend, mom, divergence)",
        "Profit lock on giveback after max seen PnL",
    ],
}

